### ISSUE TITLE
Fix checklist Markdown syntax

### ISSUE THREAD

**Issue by DominusKelvin** [sailscasts/mobile-number-issuer-detector#1]

**Comment by PrimoCrypt** [comment]
assigned

**Comment by DominusKelvin** [comment]
So I did a little research and it turns out that the GitHub task list doesn't work on ReadME, it works on only comments and issues, and PR.

So we have to close this one up, guys. Thanks again @PrimoCrypt for the quick turn around

**Comment by DominusKelvin** [comment]
For reference see this issue 👇🏾

https://github.com/github/markup/issues/208

**Comment by PrimoCrypt** [comment]
Yeah true but you can replace the space between the square brackets with x to check it

-[x] just like this

**Comment by PrimoCrypt** [comment]
Yeah true but you can replace the space between the square brackets with x to check it

- [x] just like this
