### ISSUE TITLE
Update contributors link on README.md

### ISSUE THREAD

**Issue by DominusKelvin** [sailscasts/mobile-number-issuer-detector#17]
Currently, the contributors' link still points to the old name of this project.

<img width="1047" alt="CleanShot 2023-06-15 at 08 36 13@2x" src="https://github.com/sailscasts/mobile-number-issuer-detector/assets/24433274/cd870b4a-541e-4d08-95b2-570e069dc449">

**Comment by kodezero1** [comment]
Hi, I would like to fix this issue if it's still open

**Comment by DominusKelvin** [comment]
Sure @kodezero1 since this is a community project, do make sure you are a member of the community :)

https://sailscasts.com/chat

You can join Discord and then you can submit a PR then

**Comment by kodezero1** [comment]
Alright, I'll hop on it now

**Comment by kodezero1** [comment]
Oh my bad! I didn't use contrib.rocks. Should I make changes? I'd like to hear your idea.
