### ISSUE TITLE
Filename should match exported content

### ISSUE THREAD

**Issue by geekiedj** [sailscasts/mobile-number-issuer-detector#30]
It is important that the name of each file matches what is being exported from it. This helps in maintaining clarity and ease of use for consumers of our project.

For example: instead of  `app.js` or  `predictdigit.js` , it'll be `predict-digit.js`

**Comment by Ndohjapan** [comment]
I will be working on this

**Comment by lennyAiko** [comment]
Oh i didnt catch this early
I just fixed it and made a PR, apologies
