### ISSUE TITLE
Revamp the frontend 

### ISSUE THREAD

**Issue by geekiedj** [sailscasts/mobile-number-issuer-detector#58]
The goal is to create a visually pleasing and intuitive user interface that enhances the overall user experience and incorporate changes from the CSV file.

**Comment by vulpes231** [comment]
can i work on this?

**Comment by Vixs101** [comment]
> The goal is to create a visually pleasing and intuitive user interface that enhances the overall user experience and incorporate changes from the CSV file.

So i have worked on this and created a PR. Hope you like it
