### ISSUE TITLE
Eliminate redundant comments

### ISSUE THREAD

**Issue by lennyAiko** [sailscasts/mobile-number-issuer-detector#61]
Since the variables are self descriptive, most of the comments in the code are redundant. Time to eliminate them.

**Comment by neeravbhaskarla** [comment]
Hi, can I get it assigned? I can do it.

**Comment by lennyAiko** [comment]
Sure! Have fun with it! Looking forward to your PR, will assign it to you right now

**Comment by lennyAiko** [comment]
@neeravbhaskarla , do not forget to check the contributing guidelines before making a PR ;-)

**Comment by neeravbhaskarla** [comment]
yeah sure

**Comment by neeravbhaskarla** [comment]
Hi, should I eliminate all of the comments or only the comments which are not required?

**Comment by lennyAiko** [comment]
Only the comments that are not required

**Comment by neeravbhaskarla** [comment]
okay

**Comment by geekiedj** [comment]
hey @neeravbhaskarla wanted to drop a quick note to say thanks for taking out time to make contributions to MIND! We appreciate your effort.

**Comment by neeravbhaskarla** [comment]
can you check the PR I made the required changes

**Comment by neeravbhaskarla** [comment]
I made a PR with updated changes please check.
